import fs from 'fs';

// 👇 Path to your .ttf or .woff font
const fontFile = './src/assets/fonts/NotoSansDevanagari-Regular.ttf';

const fontData = fs.readFileSync(fontFile);
const base64 = fontData.toString('base64');

// 👇 Generate a TypeScript file instead of JS
const tsContent = `
// Auto-generated by convert-font.js
const vfs: { [file: string]: string } = {
  "NotoSansDevanagari-Regular.ttf": "${base64}"
};
export default vfs;
`;

fs.writeFileSync('./src/assets/fonts/vfs_fonts.ts', tsContent);

console.log('✅ Font converted -> src/assets/fonts/vfs_fonts.ts');
